from __future__ import annotations


BASE_URL = "https://statsapi.mlb.com/api/v1"
LIVE_URL = "https://statsapi.mlb.com/api/v1.1"

SPORT_LEVELS = {
    11: "AAA",
    12: "AA",
    13: "A+",
    14: "A",
    16: "R",
}

DEFAULT_SPORT_IDS = tuple(SPORT_LEVELS)

STATIC_WHIFF_CODES = {"S", "W", "Q", "T", "M", "O"}


BATTER_COLUMNS = [
    "player_id",
    "player_name",
    "game_pk",
    "game_date",
    "season",
    "team_id",
    "team_name",
    "level",
    "ab",
    "pa",
    "h",
    "singles",
    "doubles",
    "triples",
    "hr",
    "r",
    "rbi",
    "bb",
    "ibb",
    "so",
    "hbp",
    "sf",
    "sh",
    "gdp",
    "sb",
    "cs",
    "bbe",
    "avg_ev",
    "max_ev",
    "hard_hit",
    "hard_hit_pct",
    "avg_la",
]


PITCHER_COLUMNS = [
    "player_id",
    "player_name",
    "game_pk",
    "game_date",
    "season",
    "team_id",
    "team_name",
    "level",
    "whiffs",
    "pitches",
    "batters_faced",
    "w",
    "l",
    "cg",
    "sho",
    "sv",
    "ip_outs",
    "tbf",
    "h",
    "r",
    "er",
    "hr",
    "bb",
    "ibb",
    "hbp",
    "wp",
    "bk",
    "so",
    "tracked_pitches",
    "avg_velocity",
    "max_velocity",
    "bbe_allowed",
    "avg_ev_allowed",
    "hard_hit_allowed",
    "hard_hit_pct_allowed",
]


PITCH_EVENT_COLUMNS = [
    "game_pk",
    "game_date",
    "season",
    "sport_id",
    "level",
    "inning",
    "half_inning",
    "at_bat_index",
    "event_index",
    "play_id",
    "pitch_number",
    "batter_id",
    "batter_name",
    "pitcher_id",
    "pitcher_name",
    "batter_team_id",
    "batter_team_name",
    "pitcher_team_id",
    "pitcher_team_name",
    "bat_side",
    "pitch_hand",
    "balls",
    "strikes",
    "outs",
    "pitch_type",
    "pitch_name",
    "call_code",
    "call_description",
    "event_type",
    "result_event",
    "result_description",
    "is_in_play",
    "is_strike",
    "is_ball",
    "is_out",
    "is_whiff",
    "start_speed",
    "end_speed",
    "zone",
    "plate_x",
    "plate_z",
    "extension",
    "spin_rate",
    "spin_direction",
    "break_horizontal",
    "break_vertical_induced",
    "launch_speed",
    "launch_angle",
]


BATTED_BALL_COLUMNS = [
    "game_pk",
    "game_date",
    "season",
    "sport_id",
    "level",
    "inning",
    "half_inning",
    "at_bat_index",
    "event_index",
    "play_id",
    "pitch_number",
    "batter_id",
    "batter_name",
    "pitcher_id",
    "pitcher_name",
    "batter_team_id",
    "batter_team_name",
    "pitcher_team_id",
    "pitcher_team_name",
    "bat_side",
    "pitch_hand",
    "balls",
    "strikes",
    "outs",
    "pitch_type",
    "pitch_name",
    "call_code",
    "call_description",
    "event_type",
    "result_event",
    "result_description",
    "launch_speed",
    "launch_angle",
    "total_distance",
    "trajectory",
    "hardness",
    "hit_location",
    "coord_x",
    "coord_y",
    "is_hard_hit",
]
